/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as DatasetsCreateRouteImport } from './routes/datasets/create'
import { Route as DatasetsSchemaIdIndexRouteImport } from './routes/datasets/$schemaId/index'
import { Route as DatasetsSchemaIdEntryIdRouteImport } from './routes/datasets/$schemaId/$entryId'
import { Route as DatasetsSchemaIdBulkUploadRouteImport } from './routes/datasets/$schemaId/bulk-upload'
import { Route as DatasetsSchemaIdCreateRouteImport } from './routes/datasets/$schemaId/create'
import { Route as DatasetsSchemaIdEditRouteImport } from './routes/datasets/$schemaId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsCreateRoute = DatasetsCreateRouteImport.update({
  id: '/datasets/create',
  path: '/datasets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSchemaIdIndexRoute = DatasetsSchemaIdIndexRouteImport.update({
  id: '/datasets/$schemaId/',
  path: '/datasets/$schemaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSchemaIdEntryIdRoute = DatasetsSchemaIdEntryIdRouteImport.update({
  id: '/datasets/$schemaId/$entryId',
  path: '/datasets/$schemaId/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSchemaIdBulkUploadRoute =
  DatasetsSchemaIdBulkUploadRouteImport.update({
    id: '/datasets/$schemaId/bulk-upload',
    path: '/datasets/$schemaId/bulk-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const DatasetsSchemaIdCreateRoute = DatasetsSchemaIdCreateRouteImport.update({
  id: '/datasets/$schemaId/create',
  path: '/datasets/$schemaId/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSchemaIdEditRoute = DatasetsSchemaIdEditRouteImport.update({
  id: '/datasets/$schemaId/edit',
  path: '/datasets/$schemaId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets/create': typeof DatasetsCreateRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/datasets/$schemaId/$entryId': typeof DatasetsSchemaIdEntryIdRoute
  '/datasets/$schemaId/bulk-upload': typeof DatasetsSchemaIdBulkUploadRoute
  '/datasets/$schemaId/create': typeof DatasetsSchemaIdCreateRoute
  '/datasets/$schemaId/edit': typeof DatasetsSchemaIdEditRoute
  '/datasets/$schemaId/': typeof DatasetsSchemaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets/create': typeof DatasetsCreateRoute
  '/datasets': typeof DatasetsIndexRoute
  '/datasets/$schemaId/$entryId': typeof DatasetsSchemaIdEntryIdRoute
  '/datasets/$schemaId/bulk-upload': typeof DatasetsSchemaIdBulkUploadRoute
  '/datasets/$schemaId/create': typeof DatasetsSchemaIdCreateRoute
  '/datasets/$schemaId/edit': typeof DatasetsSchemaIdEditRoute
  '/datasets/$schemaId': typeof DatasetsSchemaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets/create': typeof DatasetsCreateRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/datasets/$schemaId/$entryId': typeof DatasetsSchemaIdEntryIdRoute
  '/datasets/$schemaId/bulk-upload': typeof DatasetsSchemaIdBulkUploadRoute
  '/datasets/$schemaId/create': typeof DatasetsSchemaIdCreateRoute
  '/datasets/$schemaId/edit': typeof DatasetsSchemaIdEditRoute
  '/datasets/$schemaId/': typeof DatasetsSchemaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets/create'
    | '/datasets/'
    | '/datasets/$schemaId/$entryId'
    | '/datasets/$schemaId/bulk-upload'
    | '/datasets/$schemaId/create'
    | '/datasets/$schemaId/edit'
    | '/datasets/$schemaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets/create'
    | '/datasets'
    | '/datasets/$schemaId/$entryId'
    | '/datasets/$schemaId/bulk-upload'
    | '/datasets/$schemaId/create'
    | '/datasets/$schemaId/edit'
    | '/datasets/$schemaId'
  id:
    | '__root__'
    | '/'
    | '/datasets/create'
    | '/datasets/'
    | '/datasets/$schemaId/$entryId'
    | '/datasets/$schemaId/bulk-upload'
    | '/datasets/$schemaId/create'
    | '/datasets/$schemaId/edit'
    | '/datasets/$schemaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsCreateRoute: typeof DatasetsCreateRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  DatasetsSchemaIdEntryIdRoute: typeof DatasetsSchemaIdEntryIdRoute
  DatasetsSchemaIdBulkUploadRoute: typeof DatasetsSchemaIdBulkUploadRoute
  DatasetsSchemaIdCreateRoute: typeof DatasetsSchemaIdCreateRoute
  DatasetsSchemaIdEditRoute: typeof DatasetsSchemaIdEditRoute
  DatasetsSchemaIdIndexRoute: typeof DatasetsSchemaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/create': {
      id: '/datasets/create'
      path: '/datasets/create'
      fullPath: '/datasets/create'
      preLoaderRoute: typeof DatasetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$schemaId/': {
      id: '/datasets/$schemaId/'
      path: '/datasets/$schemaId'
      fullPath: '/datasets/$schemaId/'
      preLoaderRoute: typeof DatasetsSchemaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$schemaId/$entryId': {
      id: '/datasets/$schemaId/$entryId'
      path: '/datasets/$schemaId/$entryId'
      fullPath: '/datasets/$schemaId/$entryId'
      preLoaderRoute: typeof DatasetsSchemaIdEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$schemaId/bulk-upload': {
      id: '/datasets/$schemaId/bulk-upload'
      path: '/datasets/$schemaId/bulk-upload'
      fullPath: '/datasets/$schemaId/bulk-upload'
      preLoaderRoute: typeof DatasetsSchemaIdBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$schemaId/create': {
      id: '/datasets/$schemaId/create'
      path: '/datasets/$schemaId/create'
      fullPath: '/datasets/$schemaId/create'
      preLoaderRoute: typeof DatasetsSchemaIdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$schemaId/edit': {
      id: '/datasets/$schemaId/edit'
      path: '/datasets/$schemaId/edit'
      fullPath: '/datasets/$schemaId/edit'
      preLoaderRoute: typeof DatasetsSchemaIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsCreateRoute: DatasetsCreateRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  DatasetsSchemaIdEntryIdRoute: DatasetsSchemaIdEntryIdRoute,
  DatasetsSchemaIdBulkUploadRoute: DatasetsSchemaIdBulkUploadRoute,
  DatasetsSchemaIdCreateRoute: DatasetsSchemaIdCreateRoute,
  DatasetsSchemaIdEditRoute: DatasetsSchemaIdEditRoute,
  DatasetsSchemaIdIndexRoute: DatasetsSchemaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
