/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemasIndexRouteImport } from './routes/schemas/index'
import { Route as SchemasCreateRouteImport } from './routes/schemas/create'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as SchemasSchemaIdIndexRouteImport } from './routes/schemas/$schemaId/index'
import { Route as SchemasSchemaIdCreateRouteImport } from './routes/schemas/$schemaId/create'
import { Route as SchemasSchemaIdEntryIdRouteImport } from './routes/schemas/$schemaId/$entryId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasIndexRoute = SchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasCreateRoute = SchemasCreateRouteImport.update({
  id: '/schemas/create',
  path: '/schemas/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasSchemaIdIndexRoute = SchemasSchemaIdIndexRouteImport.update({
  id: '/schemas/$schemaId/',
  path: '/schemas/$schemaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasSchemaIdCreateRoute = SchemasSchemaIdCreateRouteImport.update({
  id: '/schemas/$schemaId/create',
  path: '/schemas/$schemaId/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasSchemaIdEntryIdRoute = SchemasSchemaIdEntryIdRouteImport.update({
  id: '/schemas/$schemaId/$entryId',
  path: '/schemas/$schemaId/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/schemas/create': typeof SchemasCreateRoute
  '/schemas/': typeof SchemasIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/schemas/$schemaId/$entryId': typeof SchemasSchemaIdEntryIdRoute
  '/schemas/$schemaId/create': typeof SchemasSchemaIdCreateRoute
  '/schemas/$schemaId/': typeof SchemasSchemaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/schemas/create': typeof SchemasCreateRoute
  '/schemas': typeof SchemasIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/schemas/$schemaId/$entryId': typeof SchemasSchemaIdEntryIdRoute
  '/schemas/$schemaId/create': typeof SchemasSchemaIdCreateRoute
  '/schemas/$schemaId': typeof SchemasSchemaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/schemas/create': typeof SchemasCreateRoute
  '/schemas/': typeof SchemasIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/schemas/$schemaId/$entryId': typeof SchemasSchemaIdEntryIdRoute
  '/schemas/$schemaId/create': typeof SchemasSchemaIdCreateRoute
  '/schemas/$schemaId/': typeof SchemasSchemaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/schemas/create'
    | '/schemas/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/schemas/$schemaId/$entryId'
    | '/schemas/$schemaId/create'
    | '/schemas/$schemaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/schemas/create'
    | '/schemas'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/schemas/$schemaId/$entryId'
    | '/schemas/$schemaId/create'
    | '/schemas/$schemaId'
  id:
    | '__root__'
    | '/'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/schemas/create'
    | '/schemas/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/schemas/$schemaId/$entryId'
    | '/schemas/$schemaId/create'
    | '/schemas/$schemaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SchemasCreateRoute: typeof SchemasCreateRoute
  SchemasIndexRoute: typeof SchemasIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  SchemasSchemaIdEntryIdRoute: typeof SchemasSchemaIdEntryIdRoute
  SchemasSchemaIdCreateRoute: typeof SchemasSchemaIdCreateRoute
  SchemasSchemaIdIndexRoute: typeof SchemasSchemaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/': {
      id: '/schemas/'
      path: '/schemas'
      fullPath: '/schemas/'
      preLoaderRoute: typeof SchemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/create': {
      id: '/schemas/create'
      path: '/schemas/create'
      fullPath: '/schemas/create'
      preLoaderRoute: typeof SchemasCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$schemaId/': {
      id: '/schemas/$schemaId/'
      path: '/schemas/$schemaId'
      fullPath: '/schemas/$schemaId/'
      preLoaderRoute: typeof SchemasSchemaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$schemaId/create': {
      id: '/schemas/$schemaId/create'
      path: '/schemas/$schemaId/create'
      fullPath: '/schemas/$schemaId/create'
      preLoaderRoute: typeof SchemasSchemaIdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$schemaId/$entryId': {
      id: '/schemas/$schemaId/$entryId'
      path: '/schemas/$schemaId/$entryId'
      fullPath: '/schemas/$schemaId/$entryId'
      preLoaderRoute: typeof SchemasSchemaIdEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SchemasCreateRoute: SchemasCreateRoute,
  SchemasIndexRoute: SchemasIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  SchemasSchemaIdEntryIdRoute: SchemasSchemaIdEntryIdRoute,
  SchemasSchemaIdCreateRoute: SchemasSchemaIdCreateRoute,
  SchemasSchemaIdIndexRoute: SchemasSchemaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
